### ISSUE TITLE
Add structure for Command Objects for all Entities

### ISSUE THREAD

**Issue by DiamondDigger** [naglec13/recipe-app#37]
### Command Object 
         - a JavaBean which will be populated with the data from your forms
Think of Command Object as a POJO/JavaBean/etc.. that backs the form in your presentation layer.

Once the form is submitted, all the individual attributes are mapped/bound to this object. On the way up to presentation, Command Object properties may be used to pre/populate the form.

**Comment by naglec13** [comment]
done.
